### ISSUE TITLE
目前只支持转换成html与json格式，有没有考虑添加转换CSV格式的功能呢？

### ISSUE THREAD

**Issue by 135zyf** [catcherwong/rdb-tools#15]
## Description

[Description of the bug or feature]

### Steps to Reproduce

1. 
2. 

### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Scope       : CLI / LIB
- Version     : 0.1.0
- System      : CentOS 7.2 (linux-x64)

**Comment by catcherwong** [comment]
csv 的话，如果有相对固定的表头，是可以添加支持的。

**Comment by 135zyf** [comment]
> csv 的话，如果有相对固定的表头，是可以添加支持的。

我使用了您开源的这个工具，比python开发的redis-rdb-tools解析的速度快太多了，固定的csv表头可以参考redis-rdb-tools类似

**Comment by catcherwong** [comment]
表头及内容暂定如下：

```csv
database,type,key,size_in_bytes,encoding,num_elements,len_largest_element
0,list,lizards,241,quicklist,5,19
0,list,user_list,190,quicklist,3,7
2,hash,baloon,138,ziplist,3,11
```

**Comment by catcherwong** [comment]
```sh
# 输出 top 50
./rdb-cli memory  /tmp/aa.rdb -ot csv

# 输出 top 200
./rdb-cli memory  /tmp/aa.rdb -ot csv -tb 200
```

**Comment by 135zyf** [comment]
非常感谢您的回复，python版rdb-tools，表头如下：
database，type，key，size_in_bytes，encoding，num_elements，len_largest_element，expiry，对于expiry过期时间的判断，您有没有考虑加进去呢？我看了下当前功能html格式的分析，对于Distribution of Key Expiration Time的分析中已经加了这个功能的判断。

**Comment by 135zyf** [comment]
后期可以考虑针对特定key的模糊匹配分析，如果有了以上表头信息的判断，再加上这个工具分析速度比较快，我相信使用它的人会远远超过[redis-rdb-tools](https://github.com/sripathikrishnan/redis-rdb-tools)，再次感谢您的贡献，对我平时的工作帮助很大！

**Comment by catcherwong** [comment]
> 对于expiry过期时间的判断，您有没有考虑加进去呢？

这个可以加

**Comment by catcherwong** [comment]
> 后期可以考虑针对特定key的模糊匹配分析

这个可以考虑，需要进行规划和测试。

**Comment by catcherwong** [comment]
![image](https://user-images.githubusercontent.com/8394988/181695078-272643fc-cc53-46d3-b3ca-6ca68ebc268f.png)

**Comment by 135zyf** [comment]
期待您提交新的版本

**Comment by catcherwong** [comment]
@135zyf  已经发布 0.5.0 版本，欢迎测试反馈。

这边这个 issue 先关闭了。如果有其他问题或建议，可以新开issue。 😄

**Comment by 135zyf** [comment]
您好，我使用了最新版，目前导出csv不支持全量的导出吗？我执行了这个命令./rdb-cli memory  /mnt/data/redis/dump.rdb -ot csv ，只导出了50个key的分析情况；分析的是14G的rdb文件，大概耗时5分钟，8核CPU耗费50%；希望能够支持导出全部的key的分析结果

**Comment by catcherwong** [comment]
这个目前是最多只支持 top x，不支持全量。

如果需要全量，需要新加一个 command 来处理。

**Comment by 135zyf** [comment]
嗯，现在只是分析top x ，14G的dump大概使用5分钟的时间，那分析全量数据的话，是不是分析时间会更久呢？
既然能够从全量数据中分析出来top X 的bigkeys，那也相当于把全量数据扫描了一遍吧！耗费时间和占用CPU方面还有待测试！

**Comment by catcherwong** [comment]
我有个疑问，把全部数据导出来csv再分析的意义在那里呢？

难道是想要在一个几百万行的csv文件上面做过滤筛选吗 😨

**Comment by 135zyf** [comment]
> 我有个疑问，把全部数据导出来csv再分析的意义在那里呢？
> 
> 难道是想要在一个几百万行的csv文件上面做过滤筛选吗 😨
不是的，不在csv文件做筛选，应用场景是这样，我们在使用缓存时，需要时刻关注缓存中的一些数据，并且做统计分析，也会做成那种可视化的数据分析看板，之前通过rdb-tools工具转换成csv文件，然后将csv文件导入mysql等数据库，然后进行查询统计的，就类似于您做的转换成html格式那种展示分析，但是想要查询某一类key前缀的数据情况，转换成html就行不通了；
所以全量数据分析的场景需求还是比较多的；rdb-tools分析速度比较慢一些，偶然之间又发现了您开源的这个项目，所以想看看对比一下哪个工具分析速度比较快一点。

**Comment by catcherwong** [comment]
方便加您微信，了解一下您这边具体的想法不？

**Comment by 135zyf** [comment]
> 方便加您微信，了解一下您这边具体的想法不？

可以的，我已经加您了
