### ISSUE TITLE
分析数据时支持按指定的key前缀来分析数据量的大小

### ISSUE THREAD

**Issue by 135zyf** [catcherwong/rdb-tools#22]
在使用工具分析RDB文件时，有个指定的配置可以设置指定的key前缀来进行具体分析，分析结果可以直接显示输出该key前缀占用的大小、总共有多少元素等，亦或者是将该key前缀的分析结果导出成html、csv文件等等

**Comment by catcherwong** [comment]
Usage

```sh
./rdb-cli csv /tmp/a.rdb -o /tmp/res/a.csv --key-prefix aaa --key-prefix bbb

./rdb-cli memory /tmp/a.rdb --key-prefix aaa --key-prefix bbb
```

**Comment by 135zyf** [comment]
您好，我使用了根据keyprefix来进行数据分析，./rdb-cli memory  dump.rdb  --key-prefix aaa:bbb:ccc -ot html -tb 200   ,当我分析这种aaa:bbb:ccc 前缀时，无法满足需求，分析结果只是aaa前缀的情况，并且数据不够准确

**Comment by catcherwong** [comment]
@135zyf  下一个版本会支持多层级的分割，应该可以满足你上面说的这个需求了。

![1666105459786](https://user-images.githubusercontent.com/8394988/196468882-eefce503-7b86-45e3-ace0-90e11e98f647.jpg)

**Comment by 135zyf** [comment]
收到



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月18日(周二) 晚上11:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [catcherwong/rdb-tools] 分析数据时支持按指定的key前缀来分析数据量的大小 (Issue #22)
