### ISSUE TITLE
是否可以支持自定义前缀分割标识符呢，或者多加几个分割符呢，例如使用 : ; , _ - + @ = | # .  等分割符号

### ISSUE THREAD

**Issue by Niceeeli** [catcherwong/rdb-tools#25]
## Description

[Description of the bug or feature]

### Steps to Reproduce

1. 
2. 

### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Scope       : CLI / LIB
- Version     : 0.1.0
- System      : CentOS 7.2 (linux-x64)

**Comment by Niceeeli** [comment]
最主要的还是支持按照"." 进行分割，历史原因 大部分key使用"." 进行分割的

**Comment by gaodg** [comment]
如果多支持分隔符，会非常方便。

**Comment by catcherwong** [comment]
计划是支持下面这些常见的

```
:    ;    ,    _    -    .
```

**Comment by catcherwong** [comment]
```sh
# 默认是 :    ;    ,    _    -    . 这几个分隔符
./rdb-cli memory /tmp/a.rdb -ot html

# 下面是指定了  :  ;  , 三个分隔符
./rdb-cli memory /tmp/a.rdb -ot html --separators :;,
```

**Comment by Niceeeli** [comment]
测试完毕没问题  非常感谢  🙏🙏🙏
