### ISSUE TITLE
Problem: long.TryParse not working right sometimes.

### ISSUE THREAD

**Issue by Phoeniwx** [catcherwong/rdb-tools#31]
## Description

工具在处理部分rdb文件时，输出结果的cTime和redis-bit为0

### Steps to Reproduce

rdb header:
![image](https://user-images.githubusercontent.com/25687584/201567886-4a1b025b-baeb-448f-805e-9a8cdd8054c5.png)

ctime实际值为1668071874，但程序分析的结果为0

### Related code
查看代码发现程序使用long.TryParse方法解析ctime，查阅.ne[t文档](https://learn.microsoft.com/en-us/dotnet/api/system.int64.tryparse?view=net-6.0)发现该方法仅用于处理十进制数字字符串
![image](https://user-images.githubusercontent.com/25687584/201569397-d5046735-4349-42e6-8eee-a72a601ec1e7.png)
因此ctime utf-8解码后包含lc就解析失败了，导致结果为0

```c#
// MemoryCallback.cs
else if (keyStr.Equals("ctime"))
{
    var time = System.Text.Encoding.UTF8.GetString(value);
    if (long.TryParse(time, out var ctime)) //这一步错误
    {
        _rdbDataInfo.CTime = ctime;
    }
}
```
我看程序中除了ctime， redis-bits，还有used-mem也使用了该方法，不知道它们是否也会在某些情况下出问题

目前我的解决方案如下：
```c#
else if (keyStr.Equals("ctime"))
{
  if (value.Length==4) {
      var ctime = System.BitConverter.ToInt32(value);
      _rdbDataInfo.CTime = ((long) ctime);
  }
```

**Comment by catcherwong** [comment]
@Phoeniwx 这个 rdb 文件是否可以提供？

**Comment by Phoeniwx** [comment]
链接: [云盘](https://pan.baidu.com/s/1V3CODZyES1dQTRgAqdiRww) 提取码: regu

**Comment by catcherwong** [comment]
重新看了一下  redis rdb 写入的方法，优化了一下这一块的解析。

 https://github.com/redis/redis/blob/e4eb18b303d716aeebc4153176a6cd93b8bd5d66/src/rdb.c#L1174-L1177

只针对 `value.Length == 4` 这个考虑还是不够的。

**Comment by Phoeniwx** [comment]
这次更新https://github.com/catcherwong/rdb-tools/commit/30bfd71affaecf8b3c36cedb4044d6f64fb86501 后ctime结果又变成0了
还是上面提到 的rdb文件

**Comment by catcherwong** [comment]
这个提交是因为太多人反馈不知道  `byte[]` 怎么转成对应的数据(字符串，数字)，所以统一在内部做好转化，外部统一用 `Encoding.UTF8.GetString` 去解析就可以了。
