### ISSUE TITLE
分析RDB文件时可否支持按expiry字段进行过滤呢？比如我导出以“aaa”为前缀，并且永不过期的所有key

### ISSUE THREAD

**Issue by 135zyf** [catcherwong/rdb-tools#33]
## Description

[Description of the bug or feature]

### Steps to Reproduce

1. 
2. 

### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Scope       : CLI / LIB
- Version     : 0.1.0
- System      : CentOS 7.2 (linux-x64)

**Comment by 135zyf** [comment]
还有这个命令：  ./rdb-cli keys dump.rdb  --key-prefix aaa  > /tmp/test.txt  不支持按前缀获取所有的key

**Comment by catcherwong** [comment]
过几天看看这个内容。

双11前后，事情比较多。

**Comment by catcherwong** [comment]
> 分析RDB文件时可否支持按expiry字段进行过滤呢？

目前支持是无过期时间和有过期时间的过滤。

```sh
# 没有过期时间限制，全部key
./rdb-cli keys /tmp/dump.rdb

# 有过期时间限制，无过期时间的key
./rdb-cli keys /tmp/dump.rdb --permanent true

# 有过期时间限制，有过期时间的key
./rdb-cli keys /tmp/dump.rdb --permanent false
```

> 还有这个命令： ./rdb-cli keys dump.rdb --key-prefix aaa > /tmp/test.txt 不支持按前缀获取所有的key

前缀这个也已经支持了。

```sh
./rdb-cli keys /tmp/dump.rdb --key-prefix aaa
```
