### ISSUE TITLE
Reading a hash field name that looks like a number

### ISSUE THREAD

**Issue by worldspawn** [catcherwong/rdb-tools#40]
## Description

[Description of the bug or feature]

### Steps to Reproduce

1. Read a hash field name that looks like an int (eg. 20000486456478)

ReadZipListEntry will enter
```
else if (entryHeader >> 4 == 14)
            {
                value = br.ReadBytes(8);
            }
```

3. Result is a set of 8 bytes that when converted to a string does not result in "20000486456478"

Sorry I understand next to nothing about how this works. I assume the bytes are correct, running them through UTF8 GetString is probably the wrong thing to do

**Comment by catcherwong** [comment]
@worldspawn  Thanks for your interest in this project.

Do you want to convert the bytes to a string (the hash field name)?

Based on you description, I need more information to solve it, could you provide a RBD file to reproduce your issue?

**Comment by worldspawn** [comment]
Its great! It has a lot of potential for me to do offline data analysis on our ~55gb dataset.

> Do you want to convert the bytes to a string (the hash field name)?

Yep. It works (running it through `UTF8.GetString()`) fine when the hash field name is a _stringy_ value like a uuid. 

[dump.zip](https://github.com/catcherwong/rdb-tools/files/10660164/dump.zip)

When this hashset is read the first key name `STRINGY` is passed to `void HSet(byte[] key, byte[] field, byte[] value)` as 7 bytes

```
83, 84, 82, 73, 78, 71, 89
```

`20000486456478` is returned as 8 bytes

```
158, 252, 227, 185, 48, 18, 0, 0,
```

**Comment by catcherwong** [comment]
```cs
else if (entryHeader >> 4 == 14)
{
        value = br.ReadBytes(8);
}
```

When enter `entryHeader >> 4 == 14`, should use `System.BitConverter.ToInt64(bytes)` to get the real value.

The value with different types will make user confuse here, there should be improved.

I will make some changes later this week and we can get the right value through `UTF8.GetString()`.

**Comment by catcherwong** [comment]
@worldspawn  We make improvement for this issue. The newest code can use `Encoding.UTF8.GetString(bytes)` to get the right value. If you also meet some issue, comment on this issue or open a new one.

**Comment by worldspawn** [comment]
Thanks @catcherwong that's working for me.

But yeah I am left with the problem of not knowing how to read the value. I'll try with your new commits.

**Comment by worldspawn** [comment]
Works great. Thanks
