### ISSUE TITLE
Add option to ignore FieldOfLargestElem

### ISSUE THREAD

**Issue by catcherwong** [catcherwong/rdb-tools#43]
## Description

When many keys contain big value, store those big value will lead to memory usage increase quickly. 

We can add an option to skip record the `FieldOfLargestElem`

### Steps to Reproduce

1. 
2. 

### Related code

```
./rdb-cli memory ./6379.rdb -ot json -tb 50
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Scope       : CLI / LIB
- Version     : 0.1.0
- System      : CentOS 7.2 (linux-x64)

**Comment by catcherwong** [comment]
```
./rdb-cli memory /tmp/dump.rdb --ignore-fole true
```

**Comment by asd626208641** [comment]
Thank you for your support , works great
