### ISSUE TITLE
支持某一后缀

### ISSUE THREAD

**Issue by Niceeeli** [catcherwong/rdb-tools#48]
## Description
业务历史原因，key前缀都不一致，导致使用rdb分析工具无法准确分析，是否可以支持某一后缀key的分析
好比一个key是  a:b:c

前缀就变成  c ,  c:b

## Specifications

- Scope       : CLI / LIB
- Version     : 0.1.0
- System      : CentOS 7.2 (linux-x64)

**Comment by catcherwong** [comment]
设置 **--key-suffix-enable**  为 true.

```sh
./rdb-cli memory /tmp/dump.rdb --key-suffix-enable true  -ot html
```
