### ISSUE TITLE
Valid values are between -62135596800000 and 253402300799999, inclusive. (Parameter 'milliseconds')

### ISSUE THREAD

**Issue by xiaobin910** [catcherwong/rdb-tools#50]
## Description

[Description of the bug or feature]

### Steps to Reproduce

1.  CentOS Linux release 7.9.2009 (Core)  执行命令 
```
nohup ./rdb-cli memory ./8-3-7003.rdb -ot html -tb 200 &
```
2. 报错信息：
Valid values are between -62135596800000 and 253402300799999, inclusive. (Parameter 'milliseconds')
Valid values are between -62135596800000 and 253402300799999, inclusive. (Parameter 'milliseconds')
Valid values are between -62135596800000 and 253402300799999, inclusive. (Parameter 'milliseconds')
........ 

### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Scope       : CLI / LIB
- Version     : 0.8.0
- System      : CentOS Linux release 7.9.2009 (Core)(linux-x64)

**Comment by catcherwong** [comment]
可以提供一个最小化的 rdb 文件复现这个吗？

**Comment by catcherwong** [comment]
version 0.9.3, fixed this issue.
