### ISSUE TITLE
支持查看已过期key某一前缀

### ISSUE THREAD

**Issue by Niceeeli** [catcherwong/rdb-tools#51]
## Description

支持查看已过期key某一前缀
### Steps to Reproduce

1. 业务可能存在大量已过期但没任何访问的key，需要查看已经过期key的前缀分别是什么，在下面tab中进行展示
![image](https://github.com/catcherwong/rdb-tools/assets/35726507/08b1a329-4f39-4241-b1b5-36dbfb76ad6e)

## Specifications

- Scope       : CLI / LIB
- Version     : 0.1.0
- System      : CentOS 7.2 (linux-x64)

**Comment by catcherwong** [comment]
这个建议用 csv 命令，导出过期的数据进行分析。

```sh
./rdb-cli csv --expired true /tmp/a.rdb
```
