### ISSUE TITLE
查看key的空闲时间

### ISSUE THREAD

**Issue by Niceeeli** [catcherwong/rdb-tools#52]
## Description
支持查看key的空闲时间分布

### Steps to Reproduce

1. RDB文件中有保存LRU空闲时间，建议增加key的空闲时间分布图，并在下面tab中增加top空闲时间的某一前缀key
### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Scope       : CLI / LIB
- Version     : 0.1.0
- System      : CentOS 7.2 (linux-x64)

**Comment by catcherwong** [comment]
空闲时间分布这个比较直观，效果如下：

![idle](https://github.com/catcherwong/rdb-tools/assets/8394988/d515aff7-4c76-4c7f-8901-81c4c2e4d625)

但是 某一前缀的 key，这个空闲时间感觉比较鸡肋，毕竟是某个前缀的 key 的 空闲时间的和，这个感觉不如单独导出 top 500 之类的 csv 会好一点。

![table](https://github.com/catcherwong/rdb-tools/assets/8394988/039b6dc8-7227-40a0-9543-bffca25efe40)

**Comment by Niceeeli** [comment]
cool，This effect is fine。
