### ISSUE TITLE
增加未设置过期时间的top Key Prefix

### ISSUE THREAD

**Issue by Niceeeli** [catcherwong/rdb-tools#53]
## Description
单独增加未设置过期时间的报表分析
### Steps to Reproduce

1. 单独增加展示未设置过期时间的top Key Prefix

### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Scope       : CLI / LIB
- Version     : 0.1.0
- System      : CentOS 7.2 (linux-x64)

**Comment by catcherwong** [comment]
这个建议用 csv 命令，导出未设置过期时间的key进行分析

```sh
./rdb-cli csv --permanent true /tmp/a.rdb
```
